name: ci
on: [push]
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libgtest-dev
      - name: Configure project
        run: cmake -S . -B build
      - name: Build project
        run: cmake --build build
      - name: Run tests
        run: cmake --build build --target test
      - name: Install project
        run: cmake --install build --prefix /tmp/root
